name: 'Slack Release Notes Action'
description: 'Publishes a release notes as a message on Slack'
branding:
  icon: message-circle
  color: blue
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  tag_name:
    description: 'Name of the tag (ex: 1.1.0). Useful, whether workflow is responsible for creating a tag (release).'
    required: false

  channel:
    description: 'Name of a slack channel (ex: general) or a channel identifier when sending in thread.'
    required: true

  thread_ts:
    description: 'Timestamp of message used as a reference to reply in thread.'
    required: false

  message:
    description: 'The text of a message that will be posted on Slack. If set, it will replace the thread_ts parameter value.'
    required: false

  release_body:
    description: 'A content of release body (e.g. a changelog).'
    required: false

  username:
    description: 'Customize the name of the bot - sender of a message. Remember to authorize `chat:write.customize scope`.'
    required: false

  icon_emoji:
    description: 'Customize an avatar by using an emoji. Remember to authorize `chat:write.customize scope`.'
    required: false

  icon_url:
    description: 'Customize bot avatar by providing an URL to image. Remember to authorize `chat:write.customize scope`.'
    required: false
